test_association:
  path: /hello/{name}
  defaults: {_controller: AcmeWorkBundle:Default:index }

work_createJob:
  path: /job/create
  defaults: { _controller: AcmeWorkBundle:Job:create }
work_indexJob:
  path: /job/index
  defaults: { _controller: AcmeWorkBundle:Job:index }
work_showJob:
  path: /job/show/{id}
  defaults: { _controller: AcmeWorkBundle:Job:show }
work_updateJob:
  path: /job/update/{id}
  defaults: { _controller: AcmeWorkBundle:Job:update }

work_createFilter:
  path: /filter/create
  defaults: { _controller: AcmeWorkBundle:Filter:create }
work_indexFilter:
  path: /filter/index
  defaults: { _controller: AcmeWorkBundle:Filter:index }
work_showFilter:
  path: /filter/show/{id}
  defaults: { _controller: AcmeWorkBundle:Filter:show }
work_updateFilter:
  path: /filter/update/{id}
  defaults: { _controller: AcmeWorkBundle:Filter:update }

work_createResume:
  path: /resume/create
  defaults: { _controller: AcmeWorkBundle:Resume:create }
work_showResume:
  path: /resume/show/{id}
  defaults: { _controller: AcmeWorkBundle:Resume:show }
work_updateResume:
  path: /resume/update/{id}
  defaults: { _controller: AcmeWorkBundle:Resume:update }
work_applyResume:
  path: /resume/apply/{id}
  defaults: { _controller: AcmeWorkBundle:Resume:apply }