test_association:
  path: /hello/{name}
  defaults: {_controller: AcmeWorkBundle:Default:index }

work_createJob:
  path: /job/create
  defaults: { _controller: AcmeWorkBundle:Job:create }
work_indexJob:
  path: /job/index
  defaults: { _controller: AcmeWorkBundle:Job:index }
work_showJob:
  path: /job/show/{id}
  defaults: { _controller: AcmeWorkBundle:Job:show }
work_updateJob:
  path: /job/update/{id}
  defaults: { _controller: AcmeWorkBundle:Job:update }

work_createResume:
  path: /resume/create
  defaults: { _controller: AcmeWorkBundle:Resume:create }
work_indexResume:
  path: /resume/index
  defaults: { _controller: AcmeWorkBundle:Resume:index }
work_showResume:
  path: /resume/show/{id}
  defaults: { _controller: AcmeWorkBundle:Resume:show }
work_updateResume:
  path: /resume/update/{id}
  defaults: { _controller: AcmeWorkBundle:Resume:update }