Acme\WorkBundle\Entity\Job:
  properties:
    title:
      - NotBlank: ~
    contact:
      - NotBlank: ~
    requiredApplication:
      - NotBlank: ~
    otherBenefit:
      - NotBlank: ~
    jobRequirement:
      - NotBlank: ~
    otherDescription:
      - NotBlank: ~
    expiredDate:
      - NotBlank: ~
Acme\WorkBundle\Entity\Resume:
  properties:
    contact:
      - NotBlank: ~
    realName:
      - NotBlank: ~
    birthday:
      - NotBlank: ~
    graduatedPlace:
      - NotBlank: ~
    falcuty:
      - NotBlank: ~
    averageScore:
      - NotBlank: ~